### ISSUE TITLE
Swap precision and recall in `MultiLabelEvaluationImpl` order 

### ISSUE THREAD

**Issue by nezda** [oracle/tribuo#121]
`MultiLabelEvaluationImpl` outputs `recall` then `precision` - feels backwards.

```
Class                           n          tp          fn          fp      recall        prec          f1
FOO                             1           0           1           0       0.000       0.000       0.000
BAR                           382         368          14          34       0.963       0.915       0.939
BAZ                            21          14           7           8       0.667       0.636       0.651
```

https://github.com/oracle/tribuo/blob/40016807de6dcac533b78bbb9e0dff50e6fb2bc4/MultiLabel/Core/src/main/java/org/tribuo/multilabel/evaluation/MultiLabelEvaluationImpl.java#L220

**Comment by Craigacp** [comment]
Both the multi-label and the multi-class classification toStrings print in that order and in the multi-class classification case it's been that way since the project was started 5 years ago (as the evaluation printing code was one of the first things written). As such we'd prefer not to rearrange the columns without sufficient reason as it would confuse our existing users.

All the metrics are available as accessors on the `Evaluation` object, and our intention is that users will generate their own output strings from that because the metrics we've chosen to put in the `[Multi]LabelEvaluation.toString()` aren't going to be universal to all problems or tasks. Some might be unnecessary and others that we aren't printing might be necessary, and the easiest way to deal with that is to allow users to build up whatever they want from it. We might look at allowing configuration in what metrics are printed to keep the nice formatting, but we've not started work on such a design effort yet as it doesn't add functionality that users can't easily write themselves.

**Comment by nezda** [comment]
I get it @Craigacp - thanks for thoughtful response. Feel free to close.
