### ISSUE TITLE
Upgrade protobuf-java version

### ISSUE THREAD

**Issue by ylwu-amzn** [oracle/tribuo#297]
**Ask the question**
I see tribuo is using 3.19.4 for protobuf-java https://github.com/oracle/tribuo/blob/main/pom.xml#LL61, which has CVE https://nvd.nist.gov/vuln/detail/CVE-2022-3171

Will you upgrade protobuf-java version ? 

**Is your question about a specific ML algorithm or approach?**
No

**Is your question about a specific Tribuo class?**
NO

**System details**
- Tribuo version: `4.2.1`
- Java version (if appropriate)
- OS/Architecture (if appropriate)

**Additional context**
Add any other context or screenshots about the question

**Comment by Craigacp** [comment]
Tribuo 4.2.2 is tagged which bumps the protobuf version to 3.19.6 which I believe has the fix in. However I think that version hasn't been pushed to Maven Central yet, which I'll start the process for tomorrow.

**Comment by Craigacp** [comment]
Tribuo 4.3.0 is already available on Maven Central which has the updated version.

**Comment by ylwu-amzn** [comment]
We are suggested to use `3.21.9`, I published a PR to force protobuf-java version https://github.com/opensearch-project/ml-commons/pull/585, testing result looks good,  any suggestion?

**Comment by Craigacp** [comment]
I've been avoiding `3.21+` because on the Python side v21 completely broke compatibility with earlier versions and was a whole mess in the Python ecosystem (it broke tensorflow, onnx and multiple other projects for a few weeks). I've not been able to test if using `3.21` causes problems writing ONNX models when reading them back in Python (or in the native code ONNX Runtime uses to parse the protobufs). If you don't care about emitting ONNX models from the stored Tribuo models then I don't think it matters too much.

**Comment by ylwu-amzn** [comment]
Thanks for the detailed explanation. We are not emitting ONNX models from tribuo models now. I think we should be good to use 3.21
