### ISSUE TITLE
Import error...

### ISSUE THREAD

**Issue by ChaJaewook** [oracle/tribuo#44]
Thank for your opensource.
It's amazing, I try to use your opensource.
But, I have some problems.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/44600628/94100226-04466e80-fe68-11ea-8e29-8598d1a20fc5.png)

I got this problem. when I set the dependency, and when we starts the code. print error like that.
plz help me... I need your help.

My version,

OS : Windows 10 
Java Version : Java 14 
JDK Vendor : OpenJDK

**Comment by Craigacp** [comment]
I don't think you need both the `loadFromPOM` and the jar magics. Either should be sufficient (assuming you've already downloaded the jars). If you haven't downloaded the jars you can use this snippet to import the necessary dependencies for the regression example:
```
%addMavenDependencies org.tribuo:tribuo-json:4.0.0
%addMavenDependencies org.tribuo:tribuo-regression-sgd:4.0.0
%addMavenDependencies org.tribuo:tribuo-regression-xgboost:4.0.0
%addMavenDependencies org.tribuo:tribuo-regression-tree:4.0.0
```
I'm not sure exactly what went wrong in your test, but I think it's a problem with how IJava is building the classpath, rather than anything to do with Tribuo.

One further thing to note is that the XGBoost jar file available on Maven Central doesn't support Windows, you'll need to compile it yourself using the MSVC compiler. This is possible but a little tricky if you've never compiled XGBoost before, and I've asked the XGBoost developers if they will add a dll to the jar file to make it simpler.

**Comment by ChaJaewook** [comment]
Hello.

First, thank you for answering the difficult question.
and, thank you for providing such a convenient source.

I read IJAVA thinking that CLASS PATH is the problem with your answers.
In conclusion, I solved it.
https://github.com/SpencerPark/IJava/issues/53
I refer to this issue.

First install the maven(I use the 3.6.3 version) 'mvn clean package' command. 
and execute the jupyter notebook. put the jar file that codes need. 
and change the name of file.

and 

%%loadFromPOM
<dependency>
    <groupId>org.tribuo</groupId>
    <artifactId>tribuo-all</artifactId>
    <version>4.0.0</version>
    <type>pom</type>
</dependency>

use this command to set the dependency.

then it works.

But still not work in xgboost environment. 
So When I use command mvn clean package that gets the error about xgboost.
But it works when execute in CART environment.

Thank you :D

**Comment by Craigacp** [comment]
Yes, unfortunately on Windows XGBoost doesn't work without compiling XGBoost (not Tribuo's XGBoost interface) yourself. Tribuo uses the xgboost jar on maven central which doesn't support Windows. Hopefully we'll be able to work with the xgboost developers to fix that.
