### ISSUE TITLE
Example(s) with Json?

### ISSUE THREAD

**Issue by aig787** [oracle/tribuo#56]
The tutorials are very helpful, but after going through them and tooling through the Javadocs I'm still not sure how I would go about loading/working with JSON data. Since it's listed as a supported format an example would be great.

**Comment by Craigacp** [comment]
JSON format data is treated as columnar data, in the same way that csv files and SQL database connections are. The current implementation (in `JsonDataSource`) assumes that the JSON file is on disk and is made up of a single array of JSON objects where each object only contains Number/String/Boolean values and should be processed into a single Tribuo `Example`.

There are lots of other ways that you could use JSON to get data into Tribuo, e.g. reading a JSON lines file, parsing a single JSON object from a String into a Tribuo `Example`, parsing more complex representations like nested maps. We've not implemented those yet because we didn't need them for our current Tribuo workloads, but we're happy to accept advice on what would be important.

Given the other issues people have raised around the loading of columnar data, we'll write a tutorial around the `RowProcessor` and it's use in `CSVDataSource` and `JsonDataSource`, and add some more docs around the use of columnar data.

**Comment by Craigacp** [comment]
As part of building a tutorial for the `RowProcessor` reading csv and json files I found some issues in the `JsonDataSource`. We'll push out a 4.0.2 point release next week with that fix in (among a few others) as it's pretty buggy in 4.0.0 and 4.0.1.

**Comment by lincolnthree** [comment]
Hey all, I'm here because I too am struggling to parse a JSON file into a JsonDataSource for a KMeans clustering prototype/PoC. Fairly lost actually.

You mentioned wanting feedback. Maybe an example of how to create a DataSource without using one of the built-in parsers would be nice. (Just using the API & built-in methods to add data to a CustomDataSource).

That way you could load the data however you want, and as long as you call the right APIs, you'll have a working datasource, without needing to use one of the built in DataSources/loaders.

You could think of it as a `ProgrammaticDataSource` or `InMemoryDataSource`.

**Comment by Craigacp** [comment]
Our version of `InMemoryDataSource` is called `ListDataSource` - https://github.com/oracle/tribuo/blob/main/Core/src/main/java/org/tribuo/datasource/ListDataSource.java

**Comment by Craigacp** [comment]
If you've got your data as a collection of `Map<String,String>` then you can feed that to a `RowProcessor` which will generate the examples for you. You'll have to wrap the `Map<String,String>` into a `ColumnarIterator.Row` object first which just makes things immutable and has an index., and then you can call `rowProcessor.generateExample()` to get the example out. We've got an example of this in the columnar tutorial which is nearly ready.

**Comment by Craigacp** [comment]
The columnar tutorial is live here - https://github.com/oracle/tribuo/blob/doc-fixes/tutorials/columnar-tribuo-v4.ipynb. It will be in the 4.0.2 release when that happens, and it currently references OLCUT 5.1.5 to get a specific fix which will also get rolled up into 4.0.2. OLCUT 5.1.5 is not on Maven central at the moment, we're working through the process to post it, but you can compile it yourself from the repo https://github.com/oracle/olcut.

**Comment by lincolnthree** [comment]
@Craigacp Thanks! This tutorial helped me get the data loaded. It makes using the intent/use behind the processor/extractor/ETL api much clearer. Nice job.

One thing I ran in to. Assuming your data is not already in CSV format... 

I had to first put the data into CSV format, write that file to disk (a temp file works fine), then pass the path to the new CSV file. This isn't a huge hassle, but is there value in allowing the `CSVDataSource` (and similar) constructors to accept an `InputStream` or even a `String` or `String[]`?

**Comment by Craigacp** [comment]
Well it depends what input format you have already. Tribuo's data sources are mostly concerned with reading things in from disk or from a database connection, as that lets them track provenance. The `ListDataSource` is designed for in memory work, and you can directly construct examples (using `ArrayExample`, `ListExample` is slower until the JVM gets value types) supplying the features you want.

We could look at accepting in memory input formats, but it would require that the stream could be read twice (as at the moment the provenance hash is calculated in a separate pass from the example construction). In general if you've got the data in memory already it's probably better to just use `ListDataSource` and run the `RowProcessor` manually over your columnar data.

If it's in another on disk format that we don't currently support then we could look at adding support for it.

**Comment by Craigacp** [comment]
We added support for parsing a Jackson `ObjectNode` into a format suitable for use in the `RowProcessor` - https://github.com/oracle/tribuo/blob/main/Json/src/main/java/org/tribuo/json/JsonUtil.java#L36.

Closing this issue for now as we've improved the documentation, if there are additional JSON features that people would like then open fresh issues so we can track it more easily.
