### ISSUE TITLE
CSVLoader.loadDataSource() Response not found

### ISSUE THREAD

**Issue by Eyal-Elbaz** [oracle/tribuo#77]
CSVLoader.loadDataSource() Response not found

`String[] feature_names = {"LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF","FullBath", "BedroomAbvGr", "TotRmsAbvGrd"};
var regressionFactory = new RegressionFactory();
var csvLoader = new CSVLoader<>(',', regressionFactory);
var houseDataSource = csvLoader.loadDataSource(Paths.get("train.csv"), "SalePrice", feature_names);`

this code results:

> Exception in thread "main" java.lang.IllegalArgumentException: Response SalePrice not found in file train.csv

[link to dataframe](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data?select=train.csv)

**Comment by Craigacp** [comment]
If you're using the `CSVLoader` you have to use the full set of columns in the file and it will read all of them. Your `feature_names` variable is treated by the `CSVLoader` as the headers of the csv file, which are already present in that csv so you don't need to supply it. The error message is because the supplied headers don't include the column you chose as the response. 

If as I think you're intending to do, you want to use a subset of the columns in that csv as features then you need to use `CSVDataSource`. You can look at the new columnar data tutorial which explains how to use the columnar processing infrastructure to load anything which isn't a csv of floats. It'll be merged into main shortly - https://github.com/oracle/tribuo/blob/doc-fixes/tutorials/columnar-tribuo-v4.ipynb, at that point you'll be able to find it in the tutorials folder and on the website when the 4.0.2 release happens.
