### ISSUE TITLE
Versions referred to in the pom.xml and tutorials may not be in sync with release 4.0.2

### ISSUE THREAD

**Issue by neomatrix369** [oracle/tribuo#92]
**Describe the bug**

The cells that load the Jars for the notebooks under https://github.com/oracle/tribuo/tree/main/tutorials are not consistently loading the Jars for version 4.0.2 as per the release version.

Also in the `pom.xml` (see [source](https://github.com/oracle/tribuo/blob/183008bde8530ec540d4b644b278f903d4e11874/pom.xml#L23)), it says `<version>4.1.0-SNAPSHOT</version>`, should this not be in sync with the release and increment each time.

**To Reproduce**

Load the notebooks using an [external docker image via here](https://github.com/neomatrix369/awesome-ai-ml-dl/tree/master/examples/tribuo#table-of-contents) (would be the same if run in native mode)

**Expected behaviour**
Tutorials and `pom.xml` be in sync with the release

**Comment by Craigacp** [comment]
No, the `main` branch is the currently in development version of Tribuo, and so has the next feature release number with SNAPSHOT appended (i.e. `4.1.0-SNAPSHOT`). The point releases which fix issues in the 4.0 series are in the `v4.0.X-release-branch`, and are tagged & versioned properly there.

I should go through and fix all the tutorials in `main` to use `4.1.0-SNAPSHOT` as the versions. Ones that haven't been revised since the initial release (e.g. the anomaly detection and clustering tutorials) should have the 4.1.0-SNAPSHOT version too, but I forgot to update them. I'll fix that today.

We keep the tutorials in the repo pegged to the version of the branch they are in so they can be updated with new in-development features, or accurately reflect a release if they are in a release tag. You'll see this in a week or so when the clustering tutorial gets updated with the new way of accessing centroids (to fix something discussed in #72) when it's merged in.

**Comment by neomatrix369** [comment]
So I have to build a docker container for each release, which branch would be best to use? Atm I'm renaming jar files to make them work with some of the tutorials, ideally would like to avoid doing that.

**Comment by Craigacp** [comment]
There will be a release branch for each minor release which contains the point releases for that version, so depending on what you want you should either use the `v4.0.X-release-branch` or a specific version tag.

**Comment by neomatrix369** [comment]
> There will be a release branch for each minor release which contains the point releases for that version, so depending on what you want you should either use the `v4.0.X-release-branch` or a specific version tag.

Perfect, `v4.0.X-release-branch` works for me!

**Comment by Craigacp** [comment]
We added a note to the main readme that describes the repo layout and where people should look for specific versions.
